### ISSUE TITLE
[RTOS] Send Display Task

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#105]
This RTOS task is responsible for updating the display. The state diagrams and some pseudocode can be found on the Google Drive (Electrical Team > Controls > New Design > Software > RTOS), but don't take either resource as absolute truth. This is the time to reason about this application code, so try to think about what exactly each module should be doing.

**Comment by babusid** [comment]
This task should be updated such that it does not signal ArrayConnection or MotorConnection. Those tasks logic should be decomposed into functions that are called directly from this task. Also, updateLights tasks should be decomposed into lights logic that is handled here.
