### ISSUE TITLE
[RTOS] Read Switches Task

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#108]
This RTOS task should read all of the input switches and set the car state accordingly. The state diagrams and some pseudocode can be found on the Google Drive (Electrical Team > Controls > New Design > Software > RTOS), but don't take either resource as absolute truth. This is the time to reason about this application code, so try to think about what exactly each module should be doing.

**Comment by babusid** [comment]
This task is now going to grow in scope, we are going to merge the logic of the UpdateLights thread into this thread, as well as array connection and motor connection handled directly by function calls here. This allows us to stop passing things through global and potentially introducing bugs.
