### ISSUE TITLE
[RTOS] Update Lights Task

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#109]
This RTOS task should update the various lights of the car depending on the internal car state. The state diagrams and some pseudocode can be found on the Google Drive (Electrical Team > Controls > New Design > Software > RTOS), but don't take either resource as absolute truth. This is the time to reason about this application code, so try to think about what exactly each module should be doing.

**Comment by babusid** [comment]
This task needs to be deprecated and rolled into function logic that is directly called by the ReadSwitches task
