### ISSUE TITLE
Pedal Driver

### ISSUE THREAD

**Issue by JimothyGreene** [lhr-solar/Controls#11]
**Summary** : This module will interact with the accelerator and brake pedals

**Requirements**:
1. Function to initialize both pedals that will call the BSP_ADC_Init with each of the pedals as parameters.
2. Function to read the position of either pedal as a percentage of the total distance. This will allow us to see how far the pedal has been pressed.

**Purpose**: This module will be called during one of the main threads of execution to determine which pedal is being pressed and how far it is being pressed. This information will be used to appropriately drive the motor controller. The specifics of those relationships will be part of the FSM.

**Comment by JimothyGreene** [comment]
What do you guys think about moving the `pedal_t` enum to this module and putting an `ADC_t `in the BSP_ADC module? Just to clarify which is which and keep the naming consistent. The `ADC_t` would be similar to the `pedal_t`, but it would consist of something like `ADC_0` and `ADC_1` so we keep the BSP_ADC module separated from the specific pieces of hardware that are connected to it. Let me know what you guys think.

**Comment by ErickCortez98** [comment]
> What do you guys think about moving the `pedal_t` enum to this module and putting an `ADC_t `in the BSP_ADC module? Just to clarify which is which and keep the naming consistent. The `ADC_t` would be similar to the `pedal_t`, but it would consist of something like `ADC_0` and `ADC_1` so we keep the BSP_ADC module separated from the specific pieces of hardware that are connected to it. Let me know what you guys think.

Yeah! I think that would be one final detail that will make the ADC module independent of any specific hardware. I like it
