### ISSUE TITLE
[RTOS] Blinker Light Task

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#110]
This RTOS task should control the blinkers -- mainly ensuring that the correct one is pulsed. The state diagrams and some pseudocode can be found on the Google Drive (Electrical Team > Controls > New Design > Software > RTOS), but don't take either resource as absolute truth. This is the time to reason about this application code, so try to think about what exactly each module should be doing.

**Comment by babusid** [comment]
Closed by PR #199
