### ISSUE TITLE
[RTOS] Send Car CAN Task

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#112]
This RTOS task is responsible for sending queued messages over CAN to other systems. The state diagrams and some pseudocode can be found on the Google Drive (Electrical Team > Controls > New Design > Software > RTOS), but don't take either resource as absolute truth. This is the time to reason about this application code, so try to think about what exactly each module should be doing.

**Comment by ClarkPoon** [comment]
@Cam0Cow if you are interested, BPS has an (untested) task that does this. The source code is [here](https://github.com/lhr-solar/BPS/blob/rtos/Apps/Src/Task_CANBusConsumer.c)
