### ISSUE TITLE
Verify Minion Board GPIOExpander port friendliness

### ISSUE THREAD

**Issue by babusid** [lhr-solar/Controls#176]
One switch on the GPIO Expander (The reverse switch, GPIOB Pin 7) shares a port with the lights. We have to make absolutely sure that at no point does this switch get set as an output because that could theoretically cause a short that breaks the GPIO expander. The file that needs to be checked is the lights driver (this file sets up GPIOB for the lights).

**Comment by babusid** [comment]
The lights and Switches initializations need to be checked.

**Comment by IshDeshpa** [comment]
Checked with the KiCAD for the Minions Board; GPIOB Pin 7 is actually not connected to anything. The port for the reverse switch is connected to GPIOA Pin 2 and the only switch connected to GPIOB is the Hazard Switch on GPIOB Pin 6.

**Comment by babusid** [comment]
@IshDeshpa is this done?

**Comment by IshDeshpa** [comment]
@babusid Yeah it's gonna be closed in the Minions Driver pull request
