### ISSUE TITLE
Pedal ADC calibration

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#206]
The low-pass filter and pull up/pull down resistors used to read the Pedal values acts as voltage dividers, skewing the results we expect. To counteract this, each pedal needs to be tuned individually (Accelerator: 0-33%, Brake: 66-99%). If need be, ask to have the pull up/down resistors replaced with higher value resistors.

**Comment by babusid** [comment]
@Cam0Cow This was fully addressed by the ADC Overhaul PR right?
