### ISSUE TITLE
Address the TODO comments in the BSP CAN Layer

### ISSUE THREAD

**Issue by babusid** [lhr-solar/Controls#209]
We have todo comments regarding some of the interrupt initialization, marking double-check locations. We should go back and confirm these items and remove the todo comments.

**Comment by NathanielDelgado** [comment]
PreemptionPriority is the priority we set the interrupt to be and SubPriority is a second-tier priority to break ties when the PreemptionPriority is the same. 

As on now, all are zero (priorities which have TODO comments) which I guess is fine. Not sure if we want to break the tie between CAN1 and CAN3 with the subpriority.
