### ISSUE TITLE
CAN Watchdog is weird

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#257]
Currently, the CAN watchdog reads a mutex protected value every five seconds to check if a chargeEnable message was sent. If it wasn't, it disables charging on its own. 

If we get timers working, this code will be completely replaced. But if not, then it can be greatly simplified and improved. Instead of checking a value protected by a mutex, just use a semaphore. ReadCarCAN can post to it, and the watchdog can pend (with a timeout of 5 seconds) and then call OSSemSet. This ensures that the interval between chargeEnables is actually at most five seconds, and not any more (the current code might not trip the watchdog for values up to 10 seconds, if we're unlucky).

**Comment by babusid** [comment]
Rolled into new issue ticket.
