### ISSUE TITLE
Fix Hard Fault on Context Switch

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#270]
When hard floats are enabled and used, the RTOS crashes on a context switch. Suspecting that it's missing the thumb_func flag on some functions in os_cpu_a.s.

Reproduce issue and check if fix works.

**Comment by babusid** [comment]
Honestly, we might just go away when we switch to FreeRTOS.

**Comment by Cam0Cow** [comment]
Software floats are working just fine for now, revisit this if necessary when we switch to FreeRTOS.
