### ISSUE TITLE
ReadCarCAN- System Review Changes

### ISSUE THREAD

**Issue by KnockbackNemo** [lhr-solar/Controls#279]
During- and slightly before- the system review, we found a few bugs in ReadCarCAN that we'd like to fix. The changes include

- Removing unnecessary header files (specifically Minions.h and CAN_Queue.h)
- Removing the line that sets OSErrLocBitmap
- Adding a conditional so that the display for array is only updated to true if restart is successful (instead of every time we attempt it)
- Moving the watchdog callback logic for alerting faultstate into chargingDisable, and then calling chargingDisable for both off messages and timer callbacks

**Comment by babusid** [comment]
Todo: Need to update this ticket to satisfy backfeed path issue from EDR
