### ISSUE TITLE
Motor Simulation

### ISSUE THREAD

**Issue by babusid** [lhr-solar/Controls#290]
# Motor Simulation Package for Renode 
## Brief Description
This package needs to be able to support a pseudo-faithful recreation of the motor controller's behavior, with respect to the messages it sends back to the control system. It is designed for us to test our velocity control code, and eventually our motor telemetry systems. **It must support both modes of controlling the motor (current control and velocity control), and some critical telemetry.** Ideally, it will be extended to support more advanced telemetry, should we choose to use it. 

## Current Control
The motor controller operates in current control mode when the given velocity setpoint is too extreme for it to reach. It continually tries to hit that extreme target, and we modulate the current that it is allowed to use, thereby allowing us to control the torque of the motor, much like a combustion vehicle.

To implement current control, we must have the facility to interpret incoming control messages, and through computation, generate an applied acceleration for the vehicle. This acceleration will be applied uniformly for 1 standard timestep of the simulation and the simulation's internal velocity must be updated. 

Some factors to consider:
- Current corresponds to torque, which in turn is directly proportional to force. It may be simplest to use a lookup table to convert incoming torque values to applied forces
- There is always a resistive force acting against the car (the sum of rolling friction and aerodynamic drag). You can use some static resistive force for now, but in the future, we may choose to model aerodynamic drag. 
- A likely control flow is: Recieve message -> interpret message -> figure out the net force -> apply uniform acceleration for one timestep -> update internal velocity.

## Velocity Control
The motor controller operates in velocity control mode when the given velocity setpoint is not too extreme for it to reach. Note, this can happen even with modulated current (ie. you can have a reachable setpoint, and still be messing with the current setpoint). **This will be more complicated than the previous section.**

The velocity control functionality of the motor controller behaves in the following manner. It measures the current error (difference between velocity setpoint, and current velocity), and attempts to correct for it by applying a certain acceleration for a certain amount of time. It then repeats this process. This is called feedback-based control. The control scheme we will be utilizing is called a **PID loop**.  

Your task is to ingest a velocity and current setpoint (the current setpoint tells you what the max force available is) and design a PID loop control system to get to that velocity setpoint over a set of timesteps. Now to go over the basics of what a PID loop is.

A PID loop stands for a "proportional-integral-derivative" loop. Each word represents one "term" in the control sequence. 
- Proportional: This term operates on the difference between where we are and where we want to be. In our case, the current velocity, and the velocity setpoint. It will be a constant multiplied by this difference. 
- Integral: This term operates on the sum of all of the errors up until now (integration of all the errors) for a given range of time. In our case, it will sum all the errors (velocity setpoint - velocity) over a given range of timesteps, and multiply it by a constant.
- Derivative: This term operates on the **rate of change for the error** (ie. the current error - previous error/timestep). It is meant to be a type of "anticipatory control" in that it tries to anticipate future errors and correct it.

I encourage you to read more about PID loops, as this is an extremely brief explanation. We can discuss this in person as well. 
(if you need help on PID @IshDeshpa has worked with them in the past so you can ask him)

Some factors to consider:
- You are still limited by the current setpoint. You will have to use it to determine the maximum force you are able to apply
- We will not need to tune the PID loop constants too much, but we will have to do it a little bit.
- Since we will have discrete forces (integers) and discrete timesteps for the simulation, we will determine a "close-enough" range to the setpoint, where the PID loop will not apply any motor torque. It will allow the resistive force to be the only force applied.

## Some thoughts on what has already been implemented
- ForceLUT: This was a pseudocode suggestion from our early brainstorming session, that I now think needs to be reworked. I don't think it's necessary, considering that it is a linear function. This can be converted to a simple mathematical relationship, defined as an inline function. This will give us more resolution (using uint8_t as the math type, you will have 0-255 discrete values that can be transformed/scaled as necessary), as well as reduce complexity.

**Comment by babusid** [comment]
@IshDeshpa Feel free to edit if you have any suggestions

**Comment by Cam0Cow** [comment]
Unnecessary. @babusid
