### ISSUE TITLE
Migrate from Standard Peripheral Library to HAL and FreeRTOS

### ISSUE THREAD

**Issue by NathanielDelgado** [lhr-solar/Controls#306]
Because the standard peripheral library (SPL) is deprecated by STM and has moved onto their new low-level layer, HAL, we want to migrate our BSP code to HAL. HAL code is easy to generate because STM32Cube MX generates the initialization code for you with an easy-to-use GUI.

Here will be a running list of new features in HAL:
- SPL is specific to a certain STM32 series but the HAL API allows for portability between series
- SPL is deprecated
- HAL has something called Full Assert which just has asserts littered in the HAL code which helps us easily debug bad parameters in HAL code. Useful for telling us we forgot to initialize something

Another thing to note is that FreeRTOS can be added to generated code from STM32Cube MX (Not sure if this is a plus since it just seems like it import the repo, but also incorporates the make file with this and brings in the correct board-specific code for the OS)

Differences that the STM32Cube MX FreeRTOS integration has:
- Generates a config file for the RTOS
- Defines and initializes the SVC and PendSV handler (needed for context switching and OS calls)
- Modifies the priority of the DMA (I guess this might matter)
- Defines the and initializes the SysTick
- Modifies the Makefile
- Brings in the FreeRTOS code into a folder called Middleware
- Configurations to FreeRTOS can be done in the STM32Cube MX GUI
- Brings in the correct port.c file to work with our specific board
- Gives us boilerplate initialization ritual to determine what we need to initialize for the RTOS

**Comment by IshDeshpa** [comment]
Being closed in Embedded-Sharepoint as the new BSP layer with HAL integration is formed.
