### ISSUE TITLE
Get rid of the os_error_loc_t enum

### ISSUE THREAD

**Issue by KnockbackNemo** [lhr-solar/Controls#333]
All the assertOSError functions require a location, but we don't actually do anything with it. The only place the enum is actually useful is in assertTaskError and Display_Error.  However, in assertTaskError it was intended to be replaced by a more proper system/enum later, and in Display_Error it will likely be deleted once we complete the issue ticket requesting changes to the display screen message.

**Comment by Cam0Cow** [comment]
> Additionally, when implementing Display_Error, we can grab the last task from the previous tasks queue and send the display the name of the task where the fault happened. This would require additional work on the display end to support being sent a string and displaying it on the fault screen.

Disregard this, the driver does not care which task the fault came from.
