### ISSUE TITLE
simulator UART stack smashing (when input is not 128bytes)

### ISSUE THREAD

**Issue by Skebob** [lhr-solar/Controls#73]
When the input from simulator GUI to UART is unexpected (the message is under 128 bytes), the program will terminate due to stack smashing.

**Comment by rafidh611** [comment]
I have been testing the UART and GUI interface and everything is working fine. I have not run into any errors. Whatever you type into the GUI prints perfectly fine on the UART CSV. I don't really know how they previously got an error.
